### ISSUE TITLE
update README sample from http to https

### ISSUE THREAD

**Issue by boly38** [zirexix/Free-Key-Value-Database#1]
when using PUT on http target, response told me : moved to https

when using PUT on https target: work fine

**Comment by pangeea** [comment]
I know that. That was a quick add-on because some users came on and start using the http://
variant, exposing the keys in clear text. Do you want me to fix anything ?
Regards,

**Comment by zirexix** [comment]
That is on purpose. There was a message on the web saying that last month but it expired.
I will add a redirect permanent from http to https sometime soon.

**Comment by zirexix** [comment]
not an issue
