### ISSUE TITLE
question about this service

### ISSUE THREAD

**Issue by boly38** [zirexix/Free-Key-Value-Database#2]
Hi,
I'm currently testing your endpoint to check if this free K,V storage could fit my needs (storage for a little game with very poor audience - eg my family)

1) the limit of this service is not very clear for me : only one tooltip [in your table ](https://www.meeiot.org/?p=start.php): is that limit correct ? I try to go under 4096 bytes but I got forbiden result, and up to 2000 was ok ?

2) do you have nodejs npm package (like https://www.npmjs.com/package/keyvalue-xyz for https://keyvalue.xyz/ service which seems to be unavailable right now) that act as meeiot client. If this not exist, and if you think it's a goot idea, it would be great to have dedicated issue (improvment)

thanks :+1:

**Comment by pangeea** [comment]
I will check that. I might be changed the code and not updated the web tool-tip or the other way around.
I will sync them as soon I have some time. Ill update the status here when I will be done.

**Comment by zirexix** [comment]
I will address that and have them in sync according to the read.me.

**Comment by zirexix** [comment]
the timing and file sizes json sizes are as in this snapshot

[https://redypis.org/phpBB3/_imgs/meiottimes.png](url)

**Comment by zirexix** [comment]
Resolved
