### ISSUE TITLE
improve throttling http status code 429 instead of 200

### ISSUE THREAD

**Issue by boly38** [zirexix/Free-Key-Value-Database#3]
You service is limited in term of query rate (that's not the subject of this issue)

When you are posting over the rate limit, you will get a 200 response with "access time < 1 seconds" payload

Here is results ` <http status code> <payload string> ` of multiples PUT then GET
``` 
200 '0:1\n'
200 '{"test":"hello2"}'
200 '0:1\n'
200 '{"test":"hello2"}'
200 '11:access time < 1 seconds\n'
200 '{"test":"hello2"}'
``` 

As application client, I would like to check wether I'm other the rate limit or not using http status
(eg. to use the payload without having to check/parse/substring payload response)

I will suggest you to use [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) as result http code (and you could keep details in payload).

` node sample.js` (using [node-rest-client](https://www.npmjs.com/package/node-rest-client)):
```
const Client = require('node-rest-client').Client; 
const meeiot_token = process.env.MEEIOT_TOKEN;
const key = "myGame";


if (!meeiot_token) {
  throw 'MEEIOT_TOKEN required';
}

var getKvCb = function getKv() {
        var getUrl = "https://meeiot.org/get/" + meeiot_token + "/" + key;
        client.get(getUrl, function (data, response) {
           console.log(response.statusCode, data.toString());
           if (data.toString().includes('access time')) {
             console.log("too quick !!");
           } else {
             console.log(JSON.parse(data.toString()).test);
           }
        });   
}

var putUrl = "https://meeiot.org/put/" + meeiot_token + "/" + key;
var client = new Client();
 		
 // set content-type header and data as json in args parameter
var args = {
 data: { test: "hello2" },
 headers: { "Content-Type": "application/json" }
};
		
client.post(putUrl, args, function (data, response) {
  console.log(response.statusCode, data.toString());
  setTimeout(getKvCb, 1000) 		
});
```

**Comment by pangeea** [comment]
Hi,
Ill look into it at the end of the week. I am dam busy with the daily job.
I might get back to you for clarification.
Thank you.

**Comment by zirexix** [comment]
Hi,
I will add the 'to many requests' HTTP code some time soon. Ill update the status here ASIDT.
Regards, Marius
