### ISSUE TITLE
secret token in url may be unsecure

### ISSUE THREAD

**Issue by boly38** [zirexix/Free-Key-Value-Database#4]
Another thing I have in mind while using your service is

Is a good idea/practice/ or is it secure to put a 'secret' token inside URL ?

According to [SO](https://stackoverflow.com/q/499591/1827276) only hostname is clear for a man-in-the-middle sniffer.

BTW on client browser side you may be able to retrieve it in history so seems a bad practice.

I think that would be great for future versions to think about that question and maybe set the token via dedicated https header.  (maybe a session based auth for activity endpoint)

**Comment by comarius** [comment]
I will add and leave also the parameter thing.
Either one has to be passed would be OK
